# Generated by Django 3.2.7 on 2021-09-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210907_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesskey',
            name='refresh_token',
        ),
        migrations.AddField(
            model_name='accesskey',
            name='id_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
