# Generated by Django 3.2.7 on 2021-09-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210908_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesskey',
            name='id_token',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
