# Generated by Django 3.2.7 on 2021-09-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_accesskey_id_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedAccessKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=50, null=True)),
                ('access_token', models.CharField(blank=True, max_length=250, null=True)),
                ('expires_in', models.IntegerField(blank=True, null=True)),
                ('token_type', models.CharField(blank=True, max_length=30, null=True)),
                ('scope', models.CharField(blank=True, max_length=500, null=True)),
                ('id_token', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
